#!/bin/bash
set -e

# 颜色定义
RED='\033[0m'
GREEN='\033[32m'
YELLOW='\033[33m'
NC='\033[0m'

# 配置变量
SERVER_IP="47.95.200.127"
DOMAIN="jianghuxiaobao.cn"
SERVER_USER="root"
APP_DIR="/var/www/jianghuxiaobao"
DATA_DIR="/var/www/jianghuxiaobao/data"

echo -e "${GREEN}=========================================${NC}"
echo -e "江湖小报部署脚本"
echo -e "服务器: ${SERVER_IP}"
echo -e "域名: ${DOMAIN}"
echo -e "=========================================${NC}"

echo -e ""
echo -e "${YELLOW}=== 第一步: 在本地构建 ===${NC}"
echo -e ""
echo -e "1. 构建前端:"
echo -e "   cd /Users/bytedance/code/jianghu/app"
echo -e "   npm run build:h5"
echo -e ""
echo -e "2. 构建后端:"
echo -e "   cd /Users/bytedance/code/jianghu/server"
echo -e "   go build -o jianghu-server ./cmd/server"
echo -e ""

echo -e "${YELLOW}=== 第二步: 上传文件到服务器 ===${NC}"
echo -e ""
echo -e "执行以下命令上传文件:"
echo -e ""
echo -e "# 创建远程目录"
echo -e "ssh ${SERVER_USER}@${SERVER_IP} \"mkdir -p ${APP_DIR}/dist ${DATA_DIR}\""
echo -e ""
echo -e "# 上传前端静态文件"
echo -e "scp -r app/dist/build/h5/* ${SERVER_USER}@${SERVER_IP}:${APP_DIR}/dist/"
echo -e ""
echo -e "# 上传后端程序"
echo -e "scp server/jianghu-server ${SERVER_USER}@${SERVER_IP}:/usr/local/bin/"
echo -e ""
echo -e "# 上传配置文件"
echo -e "scp server/deploy/config.production.yaml ${SERVER_USER}@${SERVER_IP}:/root/jianghu/config.yaml"
echo -e ""
echo -e "# 上传 Nginx 配置"
echo -e "scp server/deploy/nginx.conf ${SERVER_USER}@${SERVER_IP}:/etc/nginx/conf.d/jianghuxiaobao.conf"
echo -e ""
echo -e "# 上传 systemd 服务配置"
echo -e "scp server/deploy/jianghu.service ${SERVER_USER}@${SERVER_IP}:/etc/systemd/system/jianghu-server.service"
echo -e ""

echo -e "${YELLOW}=== 第三步: 在服务器上执行 ===${NC}"
echo -e ""
echo -e "ssh ${SERVER_USER}@${SERVER_IP}"
echo -e ""
echo -e "# 吋动配置文件"
echo -e "sed -i 's/change-this-to-random-string/$(openssl rand -hex 32)/g' /root/jianghu/config.yaml"
echo -e ""
echo -e "# 重载 systemd"
echo -e "systemctl daemon-reload"
echo -e ""
echo -e "# 启动服务"
echo -e "systemctl enable jianghu-server"
echo -e "systemctl start jianghu-server"
echo -e ""
echo -e "# 检查服务状态"
echo -e "systemctl status jianghu-server"
echo -e ""
echo -e "# 重启 Nginx"
echo -e "nginx -t && nginx -s reload"
echo -e ""
echo -e "# 检查 Nginx 状态"
echo -e "systemctl status nginx"
echo -e ""

echo -e "${GREEN}=== 部署完成 ===${NC}"
echo -e ""
echo -e "访问地址: http://${DOMAIN}"
echo -e ""
echo -e "${YELLOW}注意事项:${NC}"
echo -e "1. 确保域名 DNS 解析到服务器 IP"
echo -e "2. 修改 config.yaml 中的 JWT_SECRET 为随机字符串"
echo -e "3. 如需使用短信服务， 配置阿里云短信"
echo -e "4. 查看日志: journalctl -u jianghu-server -f"
